[App]
# User-Agent used in requests
UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"
Host = "0.0.0.0"
Port = 12312
# Running mode can be "release" or "debug"
RunningMode = "release"
RuntimeRootPath = "runtime/"

# Log related settings
LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = "log"
TimeFormat = "20060102"

[Redis]
Host = "127.0.0.1:6379"
Password = ""
MaxIdle = 30
MaxActive = 30
IdleTimeout = 200