[App]
# User-Agent used in requests
UserAgent = "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/100.0.4896.88 Safari/537.36"

RuntimeRootPath = "runtime/"

# Log related settings
LogSavePath = "logs/"
LogSaveName = "log"
LogFileExt = "log"
TimeFormat = "20060102"